version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql_db_linkify
    environment:
      MYSQL_DATABASE: linkify
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RANDOM_ROOT_PASSWOR: false
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
